### ISSUE TITLE
installation with pipx fails

### ISSUE THREAD

**Issue by v217** [gilch/hebigo#43]
I installed hebigo this way without any errors:
`
pipx install --verbose git+https://github.com/gilch/hebigo.git
`
but when running `hebi` I get this error message:
```
; hebi                                                                     
/usr/local/bin/python: Error while finding module specification for 'hebi.kernel' (ModuleNotFoundError: No module named 'hebi')
[ZMQTerminalIPythonApp] CRITICAL | Could not find existing kernel connection file kernel-6944.json
```
`pipx` is the most comfortable way to experiment with commandline tools, so that's why it would be great, if hebigo would support it. Thanks

**Comment by gilch** [comment]
Hebigo is a pre-release prototype. I don't necessarily expect an install like that to work, but you're welcome to try. It looks like you're trying to run Hebigo's REPL, which is based on IPython. IPython (or was it jupyter?) must be installed for that part to work.

Hebigo also requires Hissp, but I haven't tested it with the latest release yet. I think the parts of Hissp that Hebigo was using haven't changed much, but I wouldn't be surprised if something else broke.

See also #2.

**Comment by v217** [comment]
Ok, thanks!
`jupyter-core`, `hissp` and all the dependencies in the `setup.py`file did get installed automatically. In contrast to `pip`, where it's sometimes difficult to deinstall packages, in `pipx` it's trivial to deinstall a package and all it's dependencies, so it's really easy to play with alpha-software.

**Comment by v217** [comment]
I think the hebigo syntax is interesting! It's almost as simple as smalltalk.

**Comment by gilch** [comment]
I tried installing in a fresh virtual environment using `pip install git+https://github.com/gilch/hebigo`. I get a similar error.

Probably one of the dependencies had a major version update.

**Comment by gilch** [comment]
Looks related to https://github.com/jupyter/qtconsole/issues/54 which suggests an absolute path might help.

Looks like Hebigo's current `setup.py` was written Dec 16th, 2019. Any package released after that date might have broken it, as well as Python 3.9 itself, potentially. The only explicit dependency besides `hissp` (which looks unrelated to this error) is Jupyter Console. But it has its own dependencies. Downgrading my Jupyter Console install didn't fix it though.

**Comment by gilch** [comment]
I wonder if this is still just a race condition. I can manually start the kernel with `python -m hebi.kernel`, and then in another terminal, manually start the console with `jupyter console --existing kernel-<pid>.json`. The `<pid>` changes every time, but it's displayed in the first terminal when the kernel starts.

I have to use the `exit:` from the console to quit the kernel, and then <kbd>Ctrl+D</kbd> to quit the console, but this seems like a viable workaround for now.

The thing is, the `__main__.py` is supposed to be doing the same thing, so why isn't it working?

**Comment by gilch** [comment]
The pids don't match!

`__main__.py` is using the `pid` of the subprocess it launches, which no longer matches the name of the `.json` file. Maybe it's not a pid anymore, or maybe the subprocess is launching another subprocess.

**Comment by gilch** [comment]
After carefully reading the `jupeter console` options, I noticed that the `pid` isn't actually required. If you don't specify the `.json` file at all, it will pick the most recent active kernel. I still have to start them separately if I don't want to install a kernelspec. That's a race condition without the pid, but the Jupyter Console is for interactive use, so as long as I inform the user about what's happening, it should be fine.

@v217 try the new branch and let me know if that works: `git+https://github.com/gilch/hebigo.git@fix-repl`.

**Comment by v217** [comment]
Works great! Thank you for the fix!

**Comment by gilch** [comment]
I'll merge that in.
